# Generated by Django 3.0.8 on 2020-07-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200707_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
