# Generated by Django 3.0.8 on 2020-08-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200707_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.BigIntegerField()),
                ('year', models.IntegerField(default=1399)),
                ('month', models.CharField(default='Mordad', max_length=40)),
                ('day', models.IntegerField(default=11)),
            ],
        ),
        migrations.RemoveField(
            model_name='buy',
            name='date',
        ),
        migrations.AddField(
            model_name='buy',
            name='day',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='buy',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='buy',
            name='month',
            field=models.CharField(default='Mordad', max_length=40),
        ),
        migrations.AddField(
            model_name='buy',
            name='year',
            field=models.IntegerField(default=1399),
        ),
    ]
