# Generated by Django 3.0.8 on 2020-08-01 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200801_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='day',
            field=models.IntegerField(default=11, validators=[django.core.validators.MaxValueValidator(31)]),
        ),
    ]
