# Generated by Django 3.0.8 on 2020-08-01 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20200801_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='day',
            field=models.PositiveIntegerField(default=11, validators=[django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='buy',
            name='year',
            field=models.PositiveIntegerField(default=1399),
        ),
        migrations.AlterField(
            model_name='sell',
            name='day',
            field=models.PositiveIntegerField(default=11, validators=[django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='sell',
            name='year',
            field=models.PositiveIntegerField(default=1399),
        ),
    ]
