# Generated by Django 3.0.8 on 2020-08-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20200801_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='number',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sell',
            name='number',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
