# Generated by Django 3.0.8 on 2020-08-16 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20200803_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='day',
            field=models.PositiveIntegerField(default=26, validators=[django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='sell',
            name='day',
            field=models.PositiveIntegerField(default=26, validators=[django.core.validators.MaxValueValidator(31)]),
        ),
    ]
