# Generated by Django 3.0.8 on 2020-08-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20200819_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='description',
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='quantity',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
