# Generated by Django 3.0.8 on 2020-08-22 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20200819_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='day',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='buy',
            name='month',
            field=models.CharField(choices=[('Far', 'Farvardin'), ('Ord', 'Ordibehesht'), ('Kho', 'Khordad'), ('Tir', 'Tir'), ('Mor', 'Mordad'), ('Sha', 'Shahrivar'), ('Meh', 'Mehr'), ('Aba', 'Aban'), ('Aza', 'Azar'), ('Dey', 'Dey'), ('Bah', 'Bahman'), ('Esf', 'Esfand')], default='Sha', max_length=3),
        ),
        migrations.AlterField(
            model_name='sell',
            name='day',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='sell',
            name='month',
            field=models.CharField(choices=[('Far', 'Farvardin'), ('Ord', 'Ordibehesht'), ('Kho', 'Khordad'), ('Tir', 'Tir'), ('Mor', 'Mordad'), ('Sha', 'Shahrivar'), ('Meh', 'Mehr'), ('Aba', 'Aban'), ('Aza', 'Azar'), ('Dey', 'Dey'), ('Bah', 'Bahman'), ('Esf', 'Esfand')], default='Sha', max_length=3),
        ),
    ]
