# Generated by Django 3.0.8 on 2020-08-23 07:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20200822_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='name',
        ),
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='name',
        ),
        migrations.AddField(
            model_name='buy',
            name='stock',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='web.Stock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='stock',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='web.Stock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sell',
            name='stock',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='web.Stock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buy',
            name='day',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='sell',
            name='day',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(31)]),
        ),
    ]
