# Generated by Django 3.0.8 on 2020-08-23 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20200823_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('year', models.PositiveIntegerField(default=1399)),
                ('month', models.CharField(choices=[('Far', 'Farvardin'), ('Ord', 'Ordibehesht'), ('Kho', 'Khordad'), ('Tir', 'Tir'), ('Mor', 'Mordad'), ('Sha', 'Shahrivar'), ('Meh', 'Mehr'), ('Aba', 'Aban'), ('Aza', 'Azar'), ('Dey', 'Dey'), ('Bah', 'Bahman'), ('Esf', 'Esfand')], default='Sha', max_length=3)),
                ('day', models.PositiveIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(31)])),
            ],
        ),
    ]
