# Generated by Django 3.0.8 on 2020-08-25 17:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0023_auto_20200825_2203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deposite',
            new_name='Deposit',
        ),
    ]
