# Generated by Django 3.0.8 on 2020-08-28 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_auto_20200825_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='buy',
            name='day',
            field=models.PositiveIntegerField(default=7, validators=[django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='day',
            field=models.PositiveIntegerField(default=7, validators=[django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='sell',
            name='day',
            field=models.PositiveIntegerField(default=7, validators=[django.core.validators.MaxValueValidator(31)]),
        ),
    ]
