# Generated by Django 3.0.8 on 2020-08-28 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_auto_20200828_1434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teat',
        ),
    ]
