# Generated by Django 3.0.8 on 2020-08-16 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0003_auto_20200816_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
