# Generated by Django 3.0.8 on 2020-08-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0005_auto_20200816_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password_reset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=48)),
                ('request_date', models.DateField()),
            ],
        ),
    ]
