# Generated by Django 3.0.8 on 2020-08-17 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0007_password_reset_is_ok'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password_reset',
            old_name='is_ok',
            new_name='Is_ok',
        ),
    ]
